[build]
builder = "nixpacks"
buildCommand = "cd backend && go mod tidy"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd backend && go run main.go"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 
