[build]
builder = "nixpacks"
buildCommand = "cd backend && go mod tidy"

[deploy]
startCommand = "cd backend && go run main.go"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 
