[build]
builder = "nixpacks"
buildCommand = "cd backend && go build -o aigouda"
startCommand = "cd backend && ./main"  # 进入 backend 目录并启动应用
[deploy]
# startCommand = "./backend/aigouda"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 
